spring.application.name=chat-app-backend

spring.data.mongodb.uri=${SPRING_DATA_MONGO_URI}
spring.web.resources.static-locations=file:uploads/
cloudinary.cloud_name=dnbhfxvmz
cloudinary.api_key=948273529483918
cloudinary.api_secret=Z078RRKHjvX0cfUsdTPx2pgxWPA

